#!/bin/bash

docker run --rm --detach --privileged -it \
	--net=host \
	-v $(pwd):/mnt \
	-v $HOME/ctf:/root/ctf \
	--hostname pendock \
	--name pendock \
	pendock \
	bash \
    && echo "[+] Started"
